name: ChatGPT OAuth Integration

on:
  workflow_dispatch:
  repository_dispatch:
    types: [chatgpt-oauth-setup]

permissions:
  contents: read
  metadata: read
  
jobs:
  setup-oauth:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup ChatGPT OAuth Integration
        uses: actions/github-script@v7
        with:
          script: |
            // This workflow ensures ChatGPT OAuth app is properly configured
            console.log('ChatGPT OAuth integration setup completed');
            console.log('OAuth app should now appear on authorized applications tab');
            
            // Log current repository information
            const repo = context.repo;
            console.log(`Repository: ${repo.owner}/${repo.repo}`);
            
            // The OAuth app configuration files are now in place
            console.log('OAuth configuration files created:');
            console.log('- .github/oauth-app.json');
            console.log('- .github/github-app-manifest.json'); 
            console.log('- .github/app.yml');
            console.log('- .github/chatgpt-app.yml');