name: Lou Gehrig Fan Club - Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# No external service configurations needed for standalone website

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: .next/
        
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate deploy summary with Vercel AI
      id: vercel_ai_summary
      uses: vercel/ai-action@v2.1.0
      with:
        api-key: ${{ secrets.AI_GATEWAY_API_KEY }}
        model: 'openai/gpt-4.1-mini'
        prompt: |
          You are helping with deployment notes for the Lou Gehrig Fan Club site.
          Summarize the changes in commit ${{ github.sha }} in two sentences or fewer.
          Keep the tone professional and friendly.

    - name: Show generated summary
      if: steps.vercel_ai_summary.outputs.text != ''
      run: |
        echo "Deployment summary generated by Vercel AI:"
        echo "${{ steps.vercel_ai_summary.outputs.text }}"

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        
    - name: Health check
      run: |
        # Wait for deployment to be ready
        sleep 30
        
        # Get deployment URL from Vercel (simplified check)
        echo "Deployment completed successfully"
        echo "Remember to verify the deployment manually at your Vercel URL"