name: Structured data generation example
on:
  push:
    branches:
      - main

jobs:
  generate-recipe:
    runs-on: ubuntu-latest
    steps:
      - uses: vercel/ai-action@v2
        id: recipe
        with:
          prompt: 'Generate a lasagna recipe'
          schema: |
            {
              "$schema": "https://json-schema.org/draft/2020-12/schema",
              "type": "object",
              "properties": {
                "recipe": {
                  "type": "object",
                  "properties": {
                    "name": {"type": "string"},
                    "ingredients": {
                      "type": "array",
                      "items": {"type": "string"}
                    },
                    "steps": {
                      "type": "array",
                      "items": {"type": "string"}
                    }
                  },
                  "required": ["name", "ingredients", "steps"],
                  "additionalProperties": false
                }
              },
              "required": ["recipe"],
              "additionalProperties": false
            }
          model: 'openai/gpt-4.1'
          api-key: ${{ secrets.AI_GATEWAY_API_KEY }}
      - name: Use structured output
        run: |
          echo "Generated recipe JSON:"
          echo '${{ steps.recipe.outputs.json }}'

          # Parse and use specific fields
          echo "Recipe name: ${{ fromJson(steps.recipe.outputs.json).recipe.name }}"
